/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException

import org.openapitools.client.models.AuthenticateModel
import org.openapitools.client.models.AuthenticateResultModel
import org.openapitools.client.models.AuthenticateResultModelExtended
import org.openapitools.client.models.ExternalAuthenticateModel
import org.openapitools.client.models.ExternalAuthenticateResultModel
import org.openapitools.client.models.ExternalLoginProviderInfoModel

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class TokenAuthApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
    * 
    * 
    * @param authenticateModel  (optional)
    * @return kotlin.collections.List<AuthenticateResultModelExtended>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTokenAuthAuthenticate2Post(authenticateModel: AuthenticateModel?) : kotlin.collections.List<AuthenticateResultModelExtended> {
        val localVarResponse = apiTokenAuthAuthenticate2PostWithHttpInfo(authenticateModel = authenticateModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<AuthenticateResultModelExtended>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * 
    * 
    * @param authenticateModel  (optional)
    * @return ApiResponse<kotlin.collections.List<AuthenticateResultModelExtended>?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTokenAuthAuthenticate2PostWithHttpInfo(authenticateModel: AuthenticateModel?) : ApiResponse<kotlin.collections.List<AuthenticateResultModelExtended>?> {
        val localVariableConfig = apiTokenAuthAuthenticate2PostRequestConfig(authenticateModel = authenticateModel)

        return request<AuthenticateModel, kotlin.collections.List<AuthenticateResultModelExtended>>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation apiTokenAuthAuthenticate2Post
    *
    * @param authenticateModel  (optional)
    * @return RequestConfig
    */
    fun apiTokenAuthAuthenticate2PostRequestConfig(authenticateModel: AuthenticateModel?) : RequestConfig<AuthenticateModel> {
        val localVariableBody = authenticateModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json-patch+json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/TokenAuth/Authenticate2",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param authenticateModel  (optional)
    * @return AuthenticateResultModel
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTokenAuthAuthenticatePost(authenticateModel: AuthenticateModel?) : AuthenticateResultModel {
        val localVarResponse = apiTokenAuthAuthenticatePostWithHttpInfo(authenticateModel = authenticateModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AuthenticateResultModel
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * 
    * 
    * @param authenticateModel  (optional)
    * @return ApiResponse<AuthenticateResultModel?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTokenAuthAuthenticatePostWithHttpInfo(authenticateModel: AuthenticateModel?) : ApiResponse<AuthenticateResultModel?> {
        val localVariableConfig = apiTokenAuthAuthenticatePostRequestConfig(authenticateModel = authenticateModel)

        return request<AuthenticateModel, AuthenticateResultModel>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation apiTokenAuthAuthenticatePost
    *
    * @param authenticateModel  (optional)
    * @return RequestConfig
    */
    fun apiTokenAuthAuthenticatePostRequestConfig(authenticateModel: AuthenticateModel?) : RequestConfig<AuthenticateModel> {
        val localVariableBody = authenticateModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json-patch+json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/TokenAuth/Authenticate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param externalAuthenticateModel  (optional)
    * @return ExternalAuthenticateResultModel
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTokenAuthExternalAuthenticatePost(externalAuthenticateModel: ExternalAuthenticateModel?) : ExternalAuthenticateResultModel {
        val localVarResponse = apiTokenAuthExternalAuthenticatePostWithHttpInfo(externalAuthenticateModel = externalAuthenticateModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ExternalAuthenticateResultModel
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * 
    * 
    * @param externalAuthenticateModel  (optional)
    * @return ApiResponse<ExternalAuthenticateResultModel?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTokenAuthExternalAuthenticatePostWithHttpInfo(externalAuthenticateModel: ExternalAuthenticateModel?) : ApiResponse<ExternalAuthenticateResultModel?> {
        val localVariableConfig = apiTokenAuthExternalAuthenticatePostRequestConfig(externalAuthenticateModel = externalAuthenticateModel)

        return request<ExternalAuthenticateModel, ExternalAuthenticateResultModel>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation apiTokenAuthExternalAuthenticatePost
    *
    * @param externalAuthenticateModel  (optional)
    * @return RequestConfig
    */
    fun apiTokenAuthExternalAuthenticatePostRequestConfig(externalAuthenticateModel: ExternalAuthenticateModel?) : RequestConfig<ExternalAuthenticateModel> {
        val localVariableBody = externalAuthenticateModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json-patch+json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/TokenAuth/ExternalAuthenticate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @return kotlin.collections.List<ExternalLoginProviderInfoModel>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTokenAuthGetExternalAuthenticationProvidersGet() : kotlin.collections.List<ExternalLoginProviderInfoModel> {
        val localVarResponse = apiTokenAuthGetExternalAuthenticationProvidersGetWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ExternalLoginProviderInfoModel>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * 
    * 
    * @return ApiResponse<kotlin.collections.List<ExternalLoginProviderInfoModel>?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTokenAuthGetExternalAuthenticationProvidersGetWithHttpInfo() : ApiResponse<kotlin.collections.List<ExternalLoginProviderInfoModel>?> {
        val localVariableConfig = apiTokenAuthGetExternalAuthenticationProvidersGetRequestConfig()

        return request<Unit, kotlin.collections.List<ExternalLoginProviderInfoModel>>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation apiTokenAuthGetExternalAuthenticationProvidersGet
    *
    * @return RequestConfig
    */
    fun apiTokenAuthGetExternalAuthenticationProvidersGetRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/TokenAuth/GetExternalAuthenticationProviders",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
