/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RelojAstronomicoFecha
import org.openapitools.client.models.RelojAstronomicoHHMM

import com.squareup.moshi.Json

/**
 * 
 *
 * @param enableRelojAstronomico 
 * @param dstDayLightTime 
 * @param dstAutomatic 
 * @param offsetMinutesSunrise 
 * @param offsetMinutesSunSet 
 * @param horaSunrise 
 * @param horaSunset 
 * @param inicioVerano 
 * @param inicioInvierno 
 */

data class AstronomicalClockConfigDataDto (

    @Json(name = "enableRelojAstronomico")
    val enableRelojAstronomico: kotlin.Boolean? = null,

    @Json(name = "dstDayLightTime")
    val dstDayLightTime: kotlin.Boolean? = null,

    @Json(name = "dstAutomatic")
    val dstAutomatic: kotlin.Boolean? = null,

    @Json(name = "offsetMinutesSunrise")
    val offsetMinutesSunrise: kotlin.Int? = null,

    @Json(name = "offsetMinutesSunSet")
    val offsetMinutesSunSet: kotlin.Int? = null,

    @Json(name = "horaSunrise")
    val horaSunrise: RelojAstronomicoHHMM? = null,

    @Json(name = "horaSunset")
    val horaSunset: RelojAstronomicoHHMM? = null,

    @Json(name = "inicioVerano")
    val inicioVerano: RelojAstronomicoFecha? = null,

    @Json(name = "inicioInvierno")
    val inicioInvierno: RelojAstronomicoFecha? = null

)

