/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param unidadMedida 
 * @param valor 
 */

data class Consumo (

    @Json(name = "unidadMedida")
    val unidadMedida: kotlin.String? = null,

    @Json(name = "valor")
    val valor: kotlin.Double? = null

)

