/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param activartiempocheckbox1 
 * @param activartiempocheckbox2 
 * @param activartiempocheckbox3 
 * @param activartiempocheckbox4 
 * @param activartiempocheckbox5 
 * @param activartiempocheckbox6 
 * @param activartiempocheckbox7 
 * @param activartiempocheckbox8 
 * @param checkboxmedianochevirtual 
 * @param checkboxnivelencendido 
 * @param coraSecuenceName 
 * @param seleccionsliderEncendidoPrincipal 
 * @param seleccionsliderMedianoche 
 * @param sliderProgramacionManualMediaNoche1 
 * @param sliderProgramacionManualMediaNoche2 
 * @param sliderProgramacionManualMediaNoche3 
 * @param sliderProgramacionManualMediaNoche4 
 * @param sliderProgramacionManualMediaNoche5 
 * @param sliderProgramacionManualMediaNoche6 
 * @param sliderProgramacionManualMediaNoche7 
 * @param sliderProgramacionManualMediaNoche8 
 * @param sliderProgramacionNivelEncendido1 
 * @param sliderProgramacionNivelEncendido2 
 * @param sliderProgramacionNivelEncendido3 
 * @param sliderProgramacionNivelEncendido4 
 * @param sliderProgramacionNivelEncendido5 
 * @param sliderProgramacionNivelEncendido6 
 * @param sliderProgramacionNivelEncendido7 
 * @param sliderProgramacionNivelEncendido8 
 * @param creationTime 
 * @param tenantId 
 */

data class CoraSequenceDto (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "activartiempocheckbox_1")
    val activartiempocheckbox1: kotlin.Boolean? = null,

    @Json(name = "activartiempocheckbox_2")
    val activartiempocheckbox2: kotlin.Boolean? = null,

    @Json(name = "activartiempocheckbox_3")
    val activartiempocheckbox3: kotlin.Boolean? = null,

    @Json(name = "activartiempocheckbox_4")
    val activartiempocheckbox4: kotlin.Boolean? = null,

    @Json(name = "activartiempocheckbox_5")
    val activartiempocheckbox5: kotlin.Boolean? = null,

    @Json(name = "activartiempocheckbox_6")
    val activartiempocheckbox6: kotlin.Boolean? = null,

    @Json(name = "activartiempocheckbox_7")
    val activartiempocheckbox7: kotlin.Boolean? = null,

    @Json(name = "activartiempocheckbox_8")
    val activartiempocheckbox8: kotlin.Boolean? = null,

    @Json(name = "checkboxmedianochevirtual")
    val checkboxmedianochevirtual: kotlin.Boolean? = null,

    @Json(name = "checkboxnivelencendido")
    val checkboxnivelencendido: kotlin.Boolean? = null,

    @Json(name = "coraSecuenceName")
    val coraSecuenceName: kotlin.String? = null,

    @Json(name = "seleccionsliderEncendidoPrincipal")
    val seleccionsliderEncendidoPrincipal: kotlin.Int? = null,

    @Json(name = "seleccionsliderMedianoche")
    val seleccionsliderMedianoche: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_1")
    val sliderProgramacionManualMediaNoche1: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_2")
    val sliderProgramacionManualMediaNoche2: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_3")
    val sliderProgramacionManualMediaNoche3: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_4")
    val sliderProgramacionManualMediaNoche4: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_5")
    val sliderProgramacionManualMediaNoche5: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_6")
    val sliderProgramacionManualMediaNoche6: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_7")
    val sliderProgramacionManualMediaNoche7: kotlin.Int? = null,

    @Json(name = "sliderProgramacionManualMediaNoche_8")
    val sliderProgramacionManualMediaNoche8: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_1")
    val sliderProgramacionNivelEncendido1: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_2")
    val sliderProgramacionNivelEncendido2: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_3")
    val sliderProgramacionNivelEncendido3: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_4")
    val sliderProgramacionNivelEncendido4: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_5")
    val sliderProgramacionNivelEncendido5: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_6")
    val sliderProgramacionNivelEncendido6: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_7")
    val sliderProgramacionNivelEncendido7: kotlin.Int? = null,

    @Json(name = "sliderProgramacionNivelEncendido_8")
    val sliderProgramacionNivelEncendido8: kotlin.Int? = null,

    @Json(name = "creationTime")
    val creationTime: java.time.OffsetDateTime? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.Int? = null

)

