/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CoraAttachedLuminary
import org.openapitools.client.models.StoredFile

import com.squareup.moshi.Json

/**
 * 
 *
 * @param tenantId 
 * @param creationTime 
 * @param coraAttachedLuminaryId 
 * @param storedFileId 
 * @param id 
 * @param luminary 
 * @param storedFile 
 */

data class CoraLuminaryImage (

    @Json(name = "tenantId")
    val tenantId: kotlin.Int,

    @Json(name = "creationTime")
    val creationTime: java.time.OffsetDateTime,

    @Json(name = "coraAttachedLuminaryId")
    val coraAttachedLuminaryId: kotlin.Int,

    @Json(name = "storedFileId")
    val storedFileId: kotlin.Int,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "luminary")
    val luminary: CoraAttachedLuminary? = null,

    @Json(name = "storedFile")
    val storedFile: StoredFile? = null

)

