/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.JobStatus
import org.openapitools.client.models.JobType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param creationTime 
 * @param tenantId 
 * @param launchTime 
 * @param jobStatus 
 * @param extensionData 
 * @param jobType 
 * @param coraIDStr 
 * @param lastUpdateTime 
 * @param finishMessage 
 * @param retryNumber 
 */

data class CoraJobDto (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "creationTime")
    val creationTime: java.time.OffsetDateTime? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.Int? = null,

    @Json(name = "launchTime")
    val launchTime: java.time.OffsetDateTime? = null,

    @Json(name = "jobStatus")
    val jobStatus: JobStatus? = null,

    @Json(name = "extensionData")
    val extensionData: kotlin.String? = null,

    @Json(name = "jobType")
    val jobType: JobType? = null,

    @Json(name = "coraIDStr")
    val coraIDStr: kotlin.String? = null,

    @Json(name = "lastUpdateTime")
    val lastUpdateTime: java.time.OffsetDateTime? = null,

    @Json(name = "finishMessage")
    val finishMessage: kotlin.String? = null,

    @Json(name = "retryNumber")
    val retryNumber: kotlin.Int? = null

)

