/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param kWhSavings 
 * @param cO2KGSavings 
 * @param treesSaved 
 * @param moneySaved 
 * @param previousConsuptionKwh 
 * @param actualConsuptionKwh 
 * @param savedPowerPercentage 
 */

data class CoraSavingsResponse (

    @Json(name = "kWhSavings")
    val kWhSavings: kotlin.Double? = null,

    @Json(name = "cO2KGSavings")
    val cO2KGSavings: kotlin.Double? = null,

    @Json(name = "treesSaved")
    val treesSaved: kotlin.Double? = null,

    @Json(name = "moneySaved")
    val moneySaved: kotlin.Double? = null,

    @Json(name = "previousConsuptionKwh")
    val previousConsuptionKwh: kotlin.Double? = null,

    @Json(name = "actualConsuptionKwh")
    val actualConsuptionKwh: kotlin.Double? = null,

    @Json(name = "savedPowerPercentage")
    val savedPowerPercentage: kotlin.Double? = null

)

