/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param displayName 
 * @param id 
 * @param normalizedName 
 * @param description 
 * @param permissions 
 */

data class RoleDto (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "displayName")
    val displayName: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "normalizedName")
    val normalizedName: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "permissions")
    val permissions: kotlin.collections.List<kotlin.String>? = null

)

