/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param coraId 
 * @param launchTime 
 * @param allCoras 
 */

data class CMRModeEnableDto (

    @Json(name = "coraId")
    val coraId: kotlin.Int? = null,

    @Json(name = "launchTime")
    val launchTime: java.time.OffsetDateTime? = null,

    @Json(name = "allCoras")
    val allCoras: kotlin.Boolean? = null

)

