/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AlertType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param alertType 
 * @param userList 
 */

data class CoraAlertSubscriptionInputDto (

    @Json(name = "alertType")
    val alertType: AlertType? = null,

    @Json(name = "userList")
    val userList: kotlin.collections.List<kotlin.Int>? = null

)

