/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param kwhPrice 
 * @param kwhCo2SavingsRatio 
 * @param kwhTreeCo2Ratio 
 * @param percentajeLuminaryOnPerDay 
 * @param mapStartingLat 
 * @param mapStartingLong 
 * @param mapStartingZoom 
 * @param customOldConsumptionWh 
 */

data class CoraClientConfigurationDto (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.Int? = null,

    @Json(name = "kwhPrice")
    val kwhPrice: kotlin.Double? = null,

    @Json(name = "kwhCo2SavingsRatio")
    val kwhCo2SavingsRatio: kotlin.Double? = null,

    @Json(name = "kwhTreeCo2Ratio")
    val kwhTreeCo2Ratio: kotlin.Double? = null,

    @Json(name = "percentajeLuminaryOnPerDay")
    val percentajeLuminaryOnPerDay: kotlin.Double? = null,

    @Json(name = "mapStartingLat")
    val mapStartingLat: kotlin.Double? = null,

    @Json(name = "mapStartingLong")
    val mapStartingLong: kotlin.Double? = null,

    @Json(name = "mapStartingZoom")
    val mapStartingZoom: kotlin.Int? = null,

    @Json(name = "customOldConsumptionWh")
    val customOldConsumptionWh: kotlin.Double? = null

)

