/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param latitude 
 * @param longitude 
 * @param externalId 
 * @param description 
 * @param measuringModule 
 * @param streetType 
 * @param streetName 
 * @param localizationString 
 * @param statusString 
 */

data class CoraImportDto (

    @Json(name = "latitude")
    val latitude: kotlin.Double? = null,

    @Json(name = "longitude")
    val longitude: kotlin.Double? = null,

    @Json(name = "externalId")
    val externalId: kotlin.Int? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "measuringModule")
    val measuringModule: kotlin.String? = null,

    @Json(name = "streetType")
    val streetType: kotlin.String? = null,

    @Json(name = "streetName")
    val streetName: kotlin.String? = null,

    @Json(name = "localizationString")
    val localizationString: kotlin.String? = null,

    @Json(name = "statusString")
    val statusString: kotlin.String? = null

)

