/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AlertType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param tenantId 
 * @param alertType 
 * @param extensionData 
 * @param id 
 */

data class CoraAlertSubscription (

    @Json(name = "tenantId")
    val tenantId: kotlin.Int,

    @Json(name = "alertType")
    val alertType: AlertType,

    @Json(name = "extensionData")
    val extensionData: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int? = null

)

