/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ErrorType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param coraDescription 
 * @param errorType 
 */

data class CoraImportCheckErrorDto (

    @Json(name = "coraDescription")
    val coraDescription: kotlin.String? = null,

    @Json(name = "errorType")
    val errorType: ErrorType? = null

)

