/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UploadFileResponseDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param imageUrls 
 */

data class GetImageUrlOutputDto (

    @Json(name = "imageUrls")
    val imageUrls: kotlin.collections.List<UploadFileResponseDto>? = null

)

