/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IOTJobStatus
import org.openapitools.client.models.IOTManagementJobType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param extensionData 
 * @param iotCoraId 
 * @param iotCoraIdStr 
 * @param iotCoraGroupID 
 * @param isGroupJob 
 * @param expectedResponseNum 
 * @param responseNum 
 * @param iotJobStatus 
 * @param iotManagementJobType 
 * @param launchTime 
 * @param creationTime 
 */

data class IOTCoraManagementJobDto (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.Int? = null,

    @Json(name = "extensionData")
    val extensionData: kotlin.String? = null,

    @Json(name = "iotCoraId")
    val iotCoraId: kotlin.Int? = null,

    @Json(name = "iotCoraIdStr")
    val iotCoraIdStr: kotlin.String? = null,

    @Json(name = "iotCoraGroupID")
    val iotCoraGroupID: kotlin.Int? = null,

    @Json(name = "isGroupJob")
    val isGroupJob: kotlin.Boolean? = null,

    @Json(name = "expectedResponseNum")
    val expectedResponseNum: kotlin.Int? = null,

    @Json(name = "responseNum")
    val responseNum: kotlin.Int? = null,

    @Json(name = "iotJobStatus")
    val iotJobStatus: IOTJobStatus? = null,

    @Json(name = "iotManagementJobType")
    val iotManagementJobType: IOTManagementJobType? = null,

    @Json(name = "launchTime")
    val launchTime: java.time.OffsetDateTime? = null,

    @Json(name = "creationTime")
    val creationTime: java.time.OffsetDateTime? = null

)

