/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param p2PCoraId 
 * @param coraFirmwareUpdateFile 
 * @param launchTime 
 * @param version 
 * @param fileSize 
 */

data class P2PCoraFirmwareUpdateJobDto (

    @Json(name = "p2PCoraId")
    val p2PCoraId: kotlin.Int,

    @Json(name = "coraFirmwareUpdateFile")
    val coraFirmwareUpdateFile: kotlin.String,

    @Json(name = "launchTime")
    val launchTime: java.time.OffsetDateTime,

    @Json(name = "version")
    val version: kotlin.String,

    @Json(name = "fileSize")
    val fileSize: kotlin.Int

)

