/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.P2PCoraStatus
import org.openapitools.client.models.P2PCoraType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param coraIdStr 
 * @param description 
 * @param type 
 * @param status 
 * @param latitude 
 * @param longitude 
 * @param id 
 * @param tenantId 
 * @param swversion 
 */

data class P2PCoraDto (

    @Json(name = "coraIdStr")
    val coraIdStr: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "type")
    val type: P2PCoraType,

    @Json(name = "status")
    val status: P2PCoraStatus,

    @Json(name = "latitude")
    val latitude: kotlin.Double,

    @Json(name = "longitude")
    val longitude: kotlin.Double,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.Int? = null,

    @Json(name = "swversion")
    val swversion: kotlin.String? = null

)

