/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.P2PModulePlsStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param p2PCoraId 
 * @param plsNumber 
 * @param serialNumber 
 * @param latitude 
 * @param longitude 
 * @param id 
 * @param extensionData 
 * @param status 
 */

data class P2PModulePLSDto (

    @Json(name = "p2PCoraId")
    val p2PCoraId: kotlin.Int,

    @Json(name = "plsNumber")
    val plsNumber: kotlin.Int,

    @Json(name = "serialNumber")
    val serialNumber: kotlin.String,

    @Json(name = "latitude")
    val latitude: kotlin.Double,

    @Json(name = "longitude")
    val longitude: kotlin.Double,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "extensionData")
    val extensionData: kotlin.String? = null,

    @Json(name = "status")
    val status: P2PModulePlsStatus? = null

)

