/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param tenantId 
 * @param extensionData 
 * @param isGroupManagementReady 
 * @param coraType 
 */

data class UnifiedGroupDataDto (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.Int? = null,

    @Json(name = "extensionData")
    val extensionData: kotlin.String? = null,

    @Json(name = "isGroupManagementReady")
    val isGroupManagementReady: kotlin.Boolean? = null,

    @Json(name = "coraType")
    val coraType: kotlin.Int? = null

)

