/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param numeroFase 
 * @param tipoMedicionInstMaxMin 
 * @param tensionFaseVx10 
 * @param corrienteMA 
 * @param potenciaActivaW 
 * @param potenciaInductivaVar 
 * @param potenciaCapacitivaVar 
 * @param potenciaAparenteVA 
 * @param factorPotenciaX100 
 * @param cosenoFiX100 
 */

data class ValoresGenericos (

    @Json(name = "numeroFase")
    val numeroFase: kotlin.Int? = null,

    @Json(name = "tipoMedicionInstMaxMin")
    val tipoMedicionInstMaxMin: kotlin.Int? = null,

    @Json(name = "tensionFase_Vx10")
    val tensionFaseVx10: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "corriente_mA")
    val corrienteMA: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "potenciaActiva_W")
    val potenciaActivaW: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "potenciaInductiva_var")
    val potenciaInductivaVar: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "potenciaCapacitiva_var")
    val potenciaCapacitivaVar: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "potenciaAparente_VA")
    val potenciaAparenteVA: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "factorPotencia_x100")
    val factorPotenciaX100: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "cosenoFi_x100")
    val cosenoFiX100: kotlin.collections.List<kotlin.Int>? = null

)

