/**
 * PriluxWebUI API
 *
 * PriluxWebUI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException

import org.openapitools.client.models.AlertType
import org.openapitools.client.models.CoraAlertSubscription
import org.openapitools.client.models.CoraAlertSubscriptionInputDto

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class CoraAlertSubscriptionsServiceApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
    * 
    * 
    * @param coraAlertSubscriptionInputDto  (optional)
    * @return CoraAlertSubscription
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiServicesAppCoraAlertSubscriptionsServiceCreateOrUpdatePost(coraAlertSubscriptionInputDto: CoraAlertSubscriptionInputDto?) : CoraAlertSubscription {
        val localVarResponse = apiServicesAppCoraAlertSubscriptionsServiceCreateOrUpdatePostWithHttpInfo(coraAlertSubscriptionInputDto = coraAlertSubscriptionInputDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CoraAlertSubscription
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * 
    * 
    * @param coraAlertSubscriptionInputDto  (optional)
    * @return ApiResponse<CoraAlertSubscription?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiServicesAppCoraAlertSubscriptionsServiceCreateOrUpdatePostWithHttpInfo(coraAlertSubscriptionInputDto: CoraAlertSubscriptionInputDto?) : ApiResponse<CoraAlertSubscription?> {
        val localVariableConfig = apiServicesAppCoraAlertSubscriptionsServiceCreateOrUpdatePostRequestConfig(coraAlertSubscriptionInputDto = coraAlertSubscriptionInputDto)

        return request<CoraAlertSubscriptionInputDto, CoraAlertSubscription>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation apiServicesAppCoraAlertSubscriptionsServiceCreateOrUpdatePost
    *
    * @param coraAlertSubscriptionInputDto  (optional)
    * @return RequestConfig
    */
    fun apiServicesAppCoraAlertSubscriptionsServiceCreateOrUpdatePostRequestConfig(coraAlertSubscriptionInputDto: CoraAlertSubscriptionInputDto?) : RequestConfig<CoraAlertSubscriptionInputDto> {
        val localVariableBody = coraAlertSubscriptionInputDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json-patch+json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/services/app/CoraAlertSubscriptionsService/CreateOrUpdate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param type  (optional)
    * @return CoraAlertSubscription
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiServicesAppCoraAlertSubscriptionsServiceGetAlertSubscriptionConfigurationGet(type: AlertType?) : CoraAlertSubscription {
        val localVarResponse = apiServicesAppCoraAlertSubscriptionsServiceGetAlertSubscriptionConfigurationGetWithHttpInfo(type = type)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CoraAlertSubscription
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * 
    * 
    * @param type  (optional)
    * @return ApiResponse<CoraAlertSubscription?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiServicesAppCoraAlertSubscriptionsServiceGetAlertSubscriptionConfigurationGetWithHttpInfo(type: AlertType?) : ApiResponse<CoraAlertSubscription?> {
        val localVariableConfig = apiServicesAppCoraAlertSubscriptionsServiceGetAlertSubscriptionConfigurationGetRequestConfig(type = type)

        return request<Unit, CoraAlertSubscription>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation apiServicesAppCoraAlertSubscriptionsServiceGetAlertSubscriptionConfigurationGet
    *
    * @param type  (optional)
    * @return RequestConfig
    */
    fun apiServicesAppCoraAlertSubscriptionsServiceGetAlertSubscriptionConfigurationGetRequestConfig(type: AlertType?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/services/app/CoraAlertSubscriptionsService/GetAlertSubscriptionConfiguration",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param tenantId  (optional)
    * @return kotlin.collections.List<CoraAlertSubscription>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiServicesAppCoraAlertSubscriptionsServiceGetCoraAlertSubscriptionConfigurationsGet(tenantId: kotlin.Int?) : kotlin.collections.List<CoraAlertSubscription> {
        val localVarResponse = apiServicesAppCoraAlertSubscriptionsServiceGetCoraAlertSubscriptionConfigurationsGetWithHttpInfo(tenantId = tenantId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CoraAlertSubscription>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * 
    * 
    * @param tenantId  (optional)
    * @return ApiResponse<kotlin.collections.List<CoraAlertSubscription>?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiServicesAppCoraAlertSubscriptionsServiceGetCoraAlertSubscriptionConfigurationsGetWithHttpInfo(tenantId: kotlin.Int?) : ApiResponse<kotlin.collections.List<CoraAlertSubscription>?> {
        val localVariableConfig = apiServicesAppCoraAlertSubscriptionsServiceGetCoraAlertSubscriptionConfigurationsGetRequestConfig(tenantId = tenantId)

        return request<Unit, kotlin.collections.List<CoraAlertSubscription>>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation apiServicesAppCoraAlertSubscriptionsServiceGetCoraAlertSubscriptionConfigurationsGet
    *
    * @param tenantId  (optional)
    * @return RequestConfig
    */
    fun apiServicesAppCoraAlertSubscriptionsServiceGetCoraAlertSubscriptionConfigurationsGetRequestConfig(tenantId: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (tenantId != null) {
                    put("tenantId", listOf(tenantId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/services/app/CoraAlertSubscriptionsService/GetCoraAlertSubscriptionConfigurations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
